Repository phonebid/phonebid, pull requests merged in 2025-08, with the labels that each got.

#22 Refactor/kakao
  backend/src/main/java/com/phonebid/app/common/config/WebSecurityConfig.java
  backend/src/main/java/com/phonebid/app/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/phonebid/app/member/controller/KakaoController.java
  backend/src/main/java/com/phonebid/app/member/domain/User.java
  backend/src/main/java/com/phonebid/app/member/service/KakaoService.java
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
Labels: enhancement, feat, refactor

#25 Add login/signup (general & social), API env config, form validation, and loading state management
  .cursor/rules/architecture.mdc
  .cursor/rules/clean-code.mdc
  .cursor/rules/git-commit-message.mdc
  .cursor/rules/guideline.mdc
  .cursor/rules/prd.mdc
  .cursor/rules/step-by-step.mdc
  .vscode/launch.json
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/kakao.png
  frontend/public/naver.png
  frontend/src/App.tsx
  frontend/src/components/auth/SocialLoginButton.tsx
  frontend/src/components/common/Checkbox.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/confetti.tsx
  frontend/src/index.css
  frontend/src/lib/utils.ts
  frontend/src/pages/ConfettiPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/SignupPage.tsx
  frontend/src/services/apiClient.ts
  frontend/src/services/auctionService.ts
  frontend/src/services/authService.ts
  frontend/src/store/auctionStore.ts
  frontend/src/store/authStore.ts
  frontend/src/types/UserTypes.ts
  frontend/src/utils/constants.ts
  frontend/tailwind.config.js
  frontend/tsconfig.app.tsbuildinfo
Labels: feat

#30 feat #29: Implement User Profile APIs and Password Change APIs
  backend/src/main/java/com/phonebid/app/common/errorcode/CommonErrorCode.java
  backend/src/main/java/com/phonebid/app/member/controller/KakaoController.java
  backend/src/main/java/com/phonebid/app/member/controller/NaverController.java
  backend/src/main/java/com/phonebid/app/member/controller/UserController.java
  backend/src/main/java/com/phonebid/app/member/domain/User.java
  backend/src/main/java/com/phonebid/app/member/dto/request/LoginRequestDto.java
  backend/src/main/java/com/phonebid/app/member/dto/request/PasswordChangeRequestDto.java
  backend/src/main/java/com/phonebid/app/member/dto/request/ProfileUpdateRequestDto.java
  backend/src/main/java/com/phonebid/app/member/dto/request/SignupRequestDto.java
  backend/src/main/java/com/phonebid/app/member/dto/response/KakaoUserInfoDto.java
  backend/src/main/java/com/phonebid/app/member/dto/response/LoginResponseDto.java
  backend/src/main/java/com/phonebid/app/member/dto/response/NaverUserInfoDto.java
  backend/src/main/java/com/phonebid/app/member/dto/response/ProfileResponseDto.java
  backend/src/main/java/com/phonebid/app/member/repository/UserRepository.java
  backend/src/main/java/com/phonebid/app/member/service/KakaoService.java
  backend/src/main/java/com/phonebid/app/member/service/NaverService.java
  backend/src/main/java/com/phonebid/app/member/service/UserService.java
  backend/src/main/java/com/phonebid/app/security/JwtAuthenticationFilter.java
Labels: feat

#31 Add domain-specific error codes and replace IllegalArgumentException with customException
  backend/src/main/java/com/phonebid/app/auction/domain/Bid.java
  backend/src/main/java/com/phonebid/app/auction/domain/PricePlan.java
  backend/src/main/java/com/phonebid/app/auction/domain/Quote.java
  backend/src/main/java/com/phonebid/app/common/errorcode/AuctionErrorCode.java
  backend/src/main/java/com/phonebid/app/common/errorcode/MemberErrorCode.java
  backend/src/main/java/com/phonebid/app/common/errorcode/NotificationErrorCode.java
  backend/src/main/java/com/phonebid/app/common/errorcode/TradeErrorCode.java
  backend/src/main/java/com/phonebid/app/member/domain/Seller.java
  backend/src/main/java/com/phonebid/app/member/domain/SellerDocument.java
  backend/src/main/java/com/phonebid/app/notification/domain/Notification.java
  backend/src/main/java/com/phonebid/app/trade/domain/Contract.java
  backend/src/main/java/com/phonebid/app/trade/domain/Delivery.java
  backend/src/main/java/com/phonebid/app/trade/domain/DeliveryAddress.java
  backend/src/main/java/com/phonebid/app/trade/domain/Payment.java
  backend/src/test/java/com/phonebid/app/auction/domain/BidTest.java
  backend/src/test/java/com/phonebid/app/auction/domain/PricePlanTest.java
  backend/src/test/java/com/phonebid/app/auction/domain/QuoteTest.java
  backend/src/test/java/com/phonebid/app/member/domain/SellerTest.java
  backend/src/test/java/com/phonebid/app/trade/domain/ContractTest.java
Labels: refactor, test

#37 Develop Main Page Component & Quote Create Flow
  frontend/src/App.tsx
  frontend/src/components/common/FloatingCTA.tsx
  frontend/src/components/layout/Footer.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/quote/OptionGrid.tsx
  frontend/src/components/ranking/RankingCard.tsx
  frontend/src/pages/AuctionListPage.tsx
  frontend/src/pages/QuoteCreatePage.tsx
  frontend/src/pages/WeeklyRankingPage.tsx
  frontend/src/services/quoteService.ts
  frontend/src/store/quoteCreateStore.ts
  frontend/src/types/QuoteTypes.ts
Labels: feat

#40 Feature/seller
  backend/src/main/java/com/phonebid/app/common/errorcode/MemberErrorCode.java
  backend/src/main/java/com/phonebid/app/member/controller/SellerController.java
  backend/src/main/java/com/phonebid/app/member/domain/Seller.java
  backend/src/main/java/com/phonebid/app/member/domain/User.java
  backend/src/main/java/com/phonebid/app/member/dto/request/SellerProfileUpdateRequestDto.java
  backend/src/main/java/com/phonebid/app/member/dto/request/SellerRegisterRequestDto.java
  backend/src/main/java/com/phonebid/app/member/dto/response/SellerProfileResponseDto.java
  backend/src/main/java/com/phonebid/app/member/repository/SellerRepository.java
  backend/src/main/java/com/phonebid/app/member/service/SellerService.java
  backend/src/test/java/com/phonebid/app/member/domain/SellerTest.java
Labels: feat

#41 Feature/fetcher apply
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/SWR-GUIDE.md
  frontend/src/hooks/useSWR.ts
  frontend/src/pages/AuctionListPage.tsx
  frontend/src/providers/SWRProvider.tsx
  frontend/src/services/apiClient.ts
  frontend/src/services/swrConfig.ts
  frontend/src/types/AuctionTypes.ts
  frontend/src/utils/apiUtils.ts
Labels: feat
