Repository phonebid/phonebid, pull requests merged in 2025-07, with the labels that each got.

#7 Feature/common
  backend/build.gradle
  backend/src/main/java/com/phonebid/app/common/README.md
  backend/src/main/java/com/phonebid/app/common/config/AuditAwareImpl.java
  backend/src/main/java/com/phonebid/app/common/config/JpaConfig.java
  backend/src/main/java/com/phonebid/app/common/domain/BaseEntity.java
  backend/src/main/java/com/phonebid/app/common/dto/ApiResponse.java
  backend/src/main/java/com/phonebid/app/common/exception/CommonErrorCode.java
  backend/src/main/java/com/phonebid/app/common/exception/CustomException.java
  backend/src/main/java/com/phonebid/app/common/exception/ErrorCode.java
  backend/src/main/java/com/phonebid/app/common/exception/ErrorResponse.java
Labels: chore, feat

#9 add build.yml
  .github/workflows/build-without-test.yml
Labels: enhancement, chore

#11 Add username, password, nickname fields to User entity and refactor Role enum
  backend/src/main/java/com/phonebid/app/user/domain/Role.java
  backend/src/main/java/com/phonebid/app/user/domain/User.java
Labels: feat, refactor

#12 Feature/init entity
  .vscode/launch.json
  ERD.md
  backend/gradlew
  backend/src/main/java/com/phonebid/app/auction/domain/ActivationMethod.java
  backend/src/main/java/com/phonebid/app/auction/domain/Bid.java
  backend/src/main/java/com/phonebid/app/auction/domain/BidHistory.java
  backend/src/main/java/com/phonebid/app/auction/domain/BidStatus.java
  backend/src/main/java/com/phonebid/app/auction/domain/Carrier.java
  backend/src/main/java/com/phonebid/app/auction/domain/PricePlan.java
  backend/src/main/java/com/phonebid/app/auction/domain/PurchaseMethod.java
  backend/src/main/java/com/phonebid/app/auction/domain/Quote.java
  backend/src/main/java/com/phonebid/app/auction/domain/QuoteStatus.java
  backend/src/main/java/com/phonebid/app/common/domain/Address.java
  backend/src/main/java/com/phonebid/app/member/domain/ApprovalStatus.java
  backend/src/main/java/com/phonebid/app/member/domain/DocumentType.java
  backend/src/main/java/com/phonebid/app/member/domain/Provider.java
  backend/src/main/java/com/phonebid/app/member/domain/Role.java
  backend/src/main/java/com/phonebid/app/member/domain/Seller.java
  backend/src/main/java/com/phonebid/app/member/domain/SellerDocument.java
  backend/src/main/java/com/phonebid/app/member/domain/User.java
  backend/src/main/java/com/phonebid/app/notification/domain/Notification.java
  backend/src/main/java/com/phonebid/app/notification/domain/NotificationChannel.java
  backend/src/main/java/com/phonebid/app/notification/domain/NotificationType.java
  backend/src/main/java/com/phonebid/app/trade/domain/Contract.java
  backend/src/main/java/com/phonebid/app/trade/domain/ContractStatus.java
  backend/src/main/java/com/phonebid/app/trade/domain/Courier.java
  backend/src/main/java/com/phonebid/app/trade/domain/Delivery.java
  backend/src/main/java/com/phonebid/app/trade/domain/DeliveryAddress.java
  backend/src/main/java/com/phonebid/app/trade/domain/DeliveryStatus.java
  backend/src/main/java/com/phonebid/app/trade/domain/Payment.java
  backend/src/main/java/com/phonebid/app/trade/domain/PaymentMethod.java
  backend/src/main/java/com/phonebid/app/trade/domain/PaymentStatus.java
  backend/src/test/java/com/phonebid/app/auction/domain/BidHistoryTest.java
  backend/src/test/java/com/phonebid/app/auction/domain/BidTest.java
  backend/src/test/java/com/phonebid/app/auction/domain/PricePlanTest.java
  backend/src/test/java/com/phonebid/app/auction/domain/QuoteTest.java
  backend/src/test/java/com/phonebid/app/common/domain/AddressTest.java
  backend/src/test/java/com/phonebid/app/member/domain/SellerTest.java
  backend/src/test/java/com/phonebid/app/member/domain/UserTest.java
  backend/src/test/java/com/phonebid/app/trade/domain/ContractTest.java
  docs/API_SPECIFICATION.md
  docs/ENTITY_DESIGN.md
  docs/ERD.md
  docs/shrimp-rules.md
Labels: init

#15 Add JWT Authentication & Authorization System with Tests
  .gitignore
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/phonebid/app/jwt/JwtUtil.java
  backend/src/main/java/com/phonebid/app/member/dto/RequestDto/LoginRequestDto.java
  backend/src/main/java/com/phonebid/app/member/repository/UserRepository.java
  backend/src/main/java/com/phonebid/app/security/JwtAuthenticationFilter.java
  backend/src/main/java/com/phonebid/app/security/JwtAuthorizationFilter.java
  backend/src/main/java/com/phonebid/app/security/UserDetailsImpl.java
  backend/src/main/java/com/phonebid/app/security/UserDetailsServiceImpl.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/phonebid/app/jwt/JwtUtilTest.java
  backend/src/test/java/com/phonebid/app/security/JwtAuthenticationFilterTest.java
  backend/src/test/java/com/phonebid/app/security/JwtAuthorizationFilterTest.java
Labels: chore, feat, test

#17 Implement OAuth2 Login Flow with Social Login and Root Page Refactor
  .vscode/launch.json
  frontend/.gitignore
  frontend/eslint.config.js
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/components/auth/SocialLoginButton.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/layout/Layout.tsx
  frontend/src/pages/AuthCallbackPage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/services/authService.ts
  frontend/src/store/authStore.ts
  frontend/src/types/UserTypes.ts
  frontend/src/utils/constants.ts
  frontend/tsconfig.app.tsbuildinfo
  shrimp-rules.md
Labels: feat

#18 Implement feature login with jwt token
  backend/src/main/java/com/phonebid/app/common/config/WebSecurityConfig.java
  backend/src/main/java/com/phonebid/app/common/exception/CommonErrorCode.java
  backend/src/main/java/com/phonebid/app/member/controller/UserController.java
  backend/src/main/java/com/phonebid/app/member/dto/RequestDto/LoginRequestDto.java
  backend/src/main/java/com/phonebid/app/member/dto/ResponseDto/LoginResponseDto.java
  backend/src/main/java/com/phonebid/app/member/service/UserService.java
  backend/src/main/java/com/phonebid/app/security/JwtAuthenticationFilter.java
  backend/src/test/java/com/phonebid/app/member/service/UserServiceLoginTest.java
  backend/src/test/java/com/phonebid/app/security/JwtAuthenticationFilterTest.java
Labels: enhancement, feat, refactor, test
